cephClusterSpec:
  cephVersion:
    # renovate: image=quay.io/ceph/ceph
    image: ###ZARF_REGISTRY###/ceph/ceph:v18.2.0

  network:
    # Use host networking to avoid CNI causing storage issues
    provider: host
    # Encrypt connections to/from storage
    connections:
      encryption:
        enabled: true

  # Use select devices for storage
  storage:
    useAllNodes: true
    useAllDevices: true
    deviceFilter: "###ZARF_VAR_DEVICE_FILTER###"

imagePullSecrets:
  - name: private-registry
