package:
  create:
    max_package_size: "1000000000"
    set:
      agent_image_domain: "ghcr.io/"
      agent_image: "defenseunicorns/zarf/agent"
      agent_image_tag: "v0.31.1"

      injector_version: "2023-08-02"
      injector_amd64_shasum: "91de0768855ee2606a4f85a92bb480ff3a14ca205fd8d05eb397c18e15aa0247"
      injector_arm64_shasum: "663df681deea957b0ec53538eab221691a83de8e95d86b8a29008af711934bee"

      registry_image_domain: ""
      registry_image: "library/registry"
      registry_image_tag: "2.8.3"

      gitea_image: "gitea/gitea"
      gitea_server_version: "1.19.3"

  deploy:
    set:
      # -- Regular expression matching all devices to use for Ceph storage, example "^sd."
      # If not provided all unformatted devices and partitions will be formatted for Ceph.
      device_filter: ""
