name: clean-runner
description: "Free GH Runner Space"

runs:
  using: composite
  steps:
    - name: Free GH Runner Space
      run: |
            df -h
            sudo rm -rf /usr/share/dotnet
            sudo rm -rf /usr/local/lib/android
            sudo rm -rf /opt/ghc
            sudo rm -rf /opt/hostedtoolcache/CodeQL
            sudo docker image prune --all --force
            df -h
      shell: bash
