# After creating this resource Rook will create credentials and connection information:
# - A secret will be created in the same namespace, with the same name, that provides AWS style access keys
# - A configmap will be created in the same namespace, with the same name, that provides a host, port, and bucket name for connecting
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: test-bucket
  namespace: test
spec:
  generateBucketName: test
  storageClassName: ceph-bucket
